//! Integration tests for automated test agent policies and bot play.

use drl_core::agent::{AgentPolicy, ExplorerBot, GreedyCombatBot, RandomBot};
use drl_core::replay::ReplayEngine;
use drl_core::scenario::{Scenario, ScenarioRunner};
use drl_protocol::RunOutcome;

#[test]
fn test_random_bot_legal_actions_only() {
  let ascii = r#"
########
#@.....#
#......#
#......#
########
"#;

  let scenario =
    Scenario::from_ascii("RandomRoom", "Safety test for random actions", ascii).unwrap();
  let mut bot = RandomBot::new(777);

  let (game, events, metrics, replay) =
    ScenarioRunner::run_policy(&scenario, &mut bot, 50).unwrap();
  assert!(game.world().player().is_some());
  assert!(replay.commands.len() <= 50);
  assert!(!events.is_empty());
  assert!(metrics.turns_survived > 0);
}

#[test]
fn test_greedy_combat_bot_kills_enemy_and_descends() {
  let ascii = r#"
#########
#@..h..>#
#########
"#;

  let scenario =
    Scenario::from_ascii("DuelAndExit", "Combat encounter with stairs", ascii).unwrap();
  let mut bot = GreedyCombatBot::new();

  let (game, events, metrics, replay) =
    ScenarioRunner::run_policy(&scenario, &mut bot, 30).unwrap();

  // The bot should have engaged the former human, eliminated it, and descended stairs
  assert_eq!(metrics.outcome, RunOutcome::Victory);
  assert_eq!(metrics.enemies_killed, 1);
  assert!(metrics.damage_dealt > 0);
  assert!(game.world().level_id().0 > 1);

  // Replay generated by the bot run must be bit-exact reproducible
  let (replayed_game, replayed_events) = ReplayEngine::run(&replay).unwrap();
  assert_eq!(game, replayed_game);
  assert_eq!(events, replayed_events);
}

#[test]
fn test_explorer_bot_navigates_to_stairs() {
  let ascii = r#"
###########
#@........#
#.#.#####.#
#.#.....#.#
#.#####.#.#
#.......#.>
###########
"#;

  let scenario = Scenario::from_ascii("MazeDescent", "Labyrinth path to stairs", ascii).unwrap();
  let mut bot = ExplorerBot::new();

  let (game, events, metrics, replay) =
    ScenarioRunner::run_policy(&scenario, &mut bot, 60).unwrap();

  assert_eq!(metrics.outcome, RunOutcome::Victory);
  assert!(game.world().level_id().0 > 1);

  assert!(!events.is_empty());
  assert!(!replay.commands.is_empty());
  let is_deterministic = ReplayEngine::verify_determinism(&replay).unwrap();
  assert!(is_deterministic);
}

#[test]
fn test_agent_policy_names() {
  let random = RandomBot::new(1);
  assert_eq!(random.name(), "RandomBot");

  let combat = GreedyCombatBot::new();
  assert_eq!(combat.name(), "GreedyCombatBot");

  let explorer = ExplorerBot::new();
  assert_eq!(explorer.name(), "ExplorerBot");
}
