[package]
name = "drl-app"
description = "Application executable runner for drl-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "drl-rs"
path = "src/main.rs"

[dependencies]
drl-core = { workspace = true }
drl-mcp = { workspace = true }
drl-protocol = { workspace = true }
