//! Deterministic headless simulation core for DRL-Rust.
//!
//! This crate contains pure game simulation logic, world models, grid representation,
//! deterministic RNG, and command execution.
//! It remains strictly independent of rendering, audio, OS APIs, filesystem IO,
//! and MCP transports.

pub mod acid_spitter;
pub mod actor;
pub mod agent;
pub mod ai;
pub mod anti_freak;
pub mod assault_shotgun;
pub mod batch;
pub mod behavior;
pub mod bfg10k;
pub mod bfg9000;
pub mod chainfire;
pub mod chaingun;
pub mod combat;
pub mod combat_shotgun;
pub mod content_validation;
pub mod environment;
pub mod explosion;
pub mod fov;
pub mod game;
pub mod generator;
pub mod grammaton;
pub mod grid;
pub mod inventory;
pub mod item;
pub mod item_definition;
pub mod jackhammer;
pub mod level_definition;
pub mod loot_definition;
pub mod malek_armor;
pub mod missile_launcher;
pub mod monster_roll_definition;
pub mod nuclear_bfg9000;
pub mod nuclear_overload;
pub mod nuke;
pub mod null_pointer;
pub mod pump_action;
pub mod replay;
pub mod resistance;
pub mod rng;
pub mod rocket_launcher;
pub mod scenario;
pub mod scheduler;
pub mod special_level_definition;
pub mod subtle_knife;
pub mod targeting;
pub mod trigun;
pub mod world;

pub use actor::Actor;
pub use agent::{AgentPolicy, ExplorerBot, GreedyCombatBot, RandomBot};
pub use ai::{MonsterAction, MonsterAi};
pub use anti_freak::{
  ANTI_FREAK_JACKAL_GROUND_ITEM_DESTRUCTION_THRESHOLD, ANTI_FREAK_JACKAL_SPLASH_DICE,
  ANTI_FREAK_JACKAL_SPLASH_DIE_SIDES, radius_one_blast_positions, roll_splash_damage,
  should_destroy_ground_item, splash_knockback_direction, splash_knockback_distance,
};
pub use assault_shotgun::ASSAULT_SHOTGUN_ALT_RELOAD_CAP;
pub use batch::{
  BatchRunner, CohortComparison, CohortConfig, CohortDepthBucket, CohortDepthDistribution,
  CohortOutcomeComparison, CohortOutcomeDistribution, CohortOutcomeTolerances, CohortReport,
  CohortReportError, CohortTolerances, EpisodeRecord,
};
pub use behavior::{
  ACID_SPITTER_BEHAVIOR, ACID_SPITTER_PROJECTILE_COUNT, ACID_SPITTER_SHOT_COST,
  ANTI_FREAK_JACKAL_BEHAVIOR, ANTI_FREAK_JACKAL_EXPLOSION_DELAY,
  ANTI_FREAK_JACKAL_EXPLOSION_KNOCKBACK, ANTI_FREAK_JACKAL_EXPLOSION_RADIUS,
  ANTI_FREAK_JACKAL_PROJECTILE_COUNT, ANTI_FREAK_JACKAL_SHOT_COST, ASSAULT_SHOTGUN_BEHAVIOR,
  ActionEffect, AlternateAction, AttackEffect, BFG10K_BEHAVIOR, BFG10K_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_CHAINFIRE_SHOT_COST, BFG10K_EIGHTEENTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_EIGHTEENTH_CHAINFIRE_SHOT_COST, BFG10K_EIGHTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_EIGHTH_CHAINFIRE_SHOT_COST, BFG10K_ELEVENTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_ELEVENTH_CHAINFIRE_SHOT_COST, BFG10K_EXPLOSION_DELAY, BFG10K_EXPLOSION_KNOCKBACK,
  BFG10K_EXPLOSION_RADIUS, BFG10K_FIFTEENTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_FIFTEENTH_CHAINFIRE_SHOT_COST, BFG10K_FIFTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_FIFTH_CHAINFIRE_SHOT_COST, BFG10K_FOURTEENTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_FOURTEENTH_CHAINFIRE_SHOT_COST, BFG10K_FOURTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_FOURTH_CHAINFIRE_SHOT_COST, BFG10K_NINETEENTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_NINETEENTH_CHAINFIRE_SHOT_COST, BFG10K_NINTH_CHAINFIRE_PROJECTILE_COUNT,
  BFG10K_NINTH_CHAINFIRE_SHOT_COST, BFG10K_PROJECTILE_COUNT,
  BFG10K_SECOND_CHAINFIRE_PROJECTILE_COUNT, BFG10K_SECOND_CHAINFIRE_SHOT_COST,
  BFG10K_SEVENTEENTH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_SEVENTEENTH_CHAINFIRE_SHOT_COST,
  BFG10K_SEVENTH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_SEVENTH_CHAINFIRE_SHOT_COST, BFG10K_SHOT_COST,
  BFG10K_SIXTEENTH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_SIXTEENTH_CHAINFIRE_SHOT_COST,
  BFG10K_SIXTH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_SIXTH_CHAINFIRE_SHOT_COST,
  BFG10K_TENTH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_TENTH_CHAINFIRE_SHOT_COST,
  BFG10K_THIRD_CHAINFIRE_PROJECTILE_COUNT, BFG10K_THIRD_CHAINFIRE_SHOT_COST,
  BFG10K_THIRTEENTH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_THIRTEENTH_CHAINFIRE_SHOT_COST,
  BFG10K_TWELFTH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_TWELFTH_CHAINFIRE_SHOT_COST,
  BFG10K_TWENTIETH_CHAINFIRE_PROJECTILE_COUNT, BFG10K_TWENTIETH_CHAINFIRE_SHOT_COST,
  BFG10K_TWENTY_FIRST_CHAINFIRE_PROJECTILE_COUNT, BFG10K_TWENTY_FIRST_CHAINFIRE_SHOT_COST,
  BFG9000_BEHAVIOR, BLASTER_BEHAVIOR, BLASTER_PROJECTILE_COUNT, BLASTER_RECHARGE_AMOUNT,
  BLASTER_RECHARGE_DELAY, BLASTER_RECHARGE_TICK, BLASTER_SHOT_COST, BehaviorProfile, BehaviorSpec,
  CHAINGUN_BEHAVIOR, CHAINGUN_EIGHTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_EIGHTH_CHAINFIRE_SHOT_COST, CHAINGUN_ELEVENTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_ELEVENTH_CHAINFIRE_SHOT_COST, CHAINGUN_FIFTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_FOURTEENTH_CHAINFIRE_PROJECTILE_COUNT, CHAINGUN_FOURTEENTH_CHAINFIRE_SHOT_COST,
  CHAINGUN_FOURTH_CHAINFIRE_PROJECTILE_COUNT, CHAINGUN_FOURTH_CHAINFIRE_SHOT_COST,
  CHAINGUN_NINTH_CHAINFIRE_PROJECTILE_COUNT, CHAINGUN_NINTH_CHAINFIRE_SHOT_COST,
  CHAINGUN_PROJECTILE_COUNT, CHAINGUN_SECOND_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_SECOND_CHAINFIRE_SHOT_COST, CHAINGUN_SEVENTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_SEVENTH_CHAINFIRE_SHOT_COST, CHAINGUN_SIXTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_SIXTH_CHAINFIRE_SHOT_COST, CHAINGUN_TENTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_TENTH_CHAINFIRE_SHOT_COST, CHAINGUN_THIRD_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_THIRD_CHAINFIRE_SHOT_COST, CHAINGUN_THIRTEENTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_THIRTEENTH_CHAINFIRE_SHOT_COST, CHAINGUN_TWELFTH_CHAINFIRE_PROJECTILE_COUNT,
  CHAINGUN_TWELFTH_CHAINFIRE_SHOT_COST, COMBAT_PISTOL_BEHAVIOR, COMBAT_PISTOL_PROJECTILE_COUNT,
  COMBAT_SHOTGUN_BEHAVIOR, DOUBLE_SHOTGUN_BEHAVIOR, EquipEffect, FRAG_SHOTGUN_BEHAVIOR,
  FRAG_SHOTGUN_PROJECTILE_COUNT, FRAG_SHOTGUN_SHOT_COST, GRAMMATON_BEHAVIOR, HitEffect, ItemSetId,
  JACKHAMMER_BEHAVIOR, KillEffect, LASER_RIFLE_BEHAVIOR, LASER_RIFLE_CHAINFIRE_PROJECTILE_COUNT,
  LASER_RIFLE_CHAINFIRE_SHOT_COST, LASER_RIFLE_FIFTH_CHAINFIRE_PROJECTILE_COUNT,
  LASER_RIFLE_FIFTH_CHAINFIRE_SHOT_COST, LASER_RIFLE_FOURTH_CHAINFIRE_PROJECTILE_COUNT,
  LASER_RIFLE_FOURTH_CHAINFIRE_SHOT_COST, LASER_RIFLE_PROJECTILE_COUNT,
  LASER_RIFLE_SECOND_CHAINFIRE_PROJECTILE_COUNT, LASER_RIFLE_SECOND_CHAINFIRE_SHOT_COST,
  LASER_RIFLE_SEVENTH_CHAINFIRE_PROJECTILE_COUNT, LASER_RIFLE_SEVENTH_CHAINFIRE_SHOT_COST,
  LASER_RIFLE_SIXTH_CHAINFIRE_PROJECTILE_COUNT, LASER_RIFLE_SIXTH_CHAINFIRE_SHOT_COST,
  LASER_RIFLE_THIRD_CHAINFIRE_PROJECTILE_COUNT, LASER_RIFLE_THIRD_CHAINFIRE_SHOT_COST,
  LAVA_ARMOR_BEHAVIOR, MALEK_ARMOR_BEHAVIOR, MEDICAL_POWERARMOR_BEHAVIOR, MEDICAL_REPAIR_INTERVAL,
  MEDICAL_REPAIR_MIN_DURABILITY_EXCLUSIVE, MEDICAL_REPAIR_TIMER_AFTER_REPAIR, MEGA_BUSTER_BEHAVIOR,
  MEGA_BUSTER_PROJECTILE_COUNT, MEGA_BUSTER_SHOT_COST, MINIGUN_BEHAVIOR,
  MINIGUN_CHAINFIRE_PROJECTILE_COUNT, MINIGUN_CHAINFIRE_SHOT_COST, MINIGUN_PROJECTILE_COUNT,
  MINIGUN_SECOND_CHAINFIRE_PROJECTILE_COUNT, MINIGUN_SECOND_CHAINFIRE_SHOT_COST,
  MINIGUN_THIRD_CHAINFIRE_PROJECTILE_COUNT, MINIGUN_THIRD_CHAINFIRE_SHOT_COST,
  MISSILE_LAUNCHER_BEHAVIOR, MedicalRepairOutcome, MedicalRepairState, NUCLEAR_BFG_RECHARGE_AMOUNT,
  NUCLEAR_BFG_RECHARGE_DELAY, NUCLEAR_BFG_RECHARGE_TICK, NUCLEAR_BFG9000_BEHAVIOR,
  NUCLEAR_PLASMA_BEHAVIOR, NUCLEAR_PLASMA_CHAINFIRE_PROJECTILE_COUNT,
  NUCLEAR_PLASMA_CHAINFIRE_SHOT_COST, NUCLEAR_PLASMA_FIFTH_CHAINFIRE_PROJECTILE_COUNT,
  NUCLEAR_PLASMA_FIFTH_CHAINFIRE_SHOT_COST, NUCLEAR_PLASMA_FOURTH_CHAINFIRE_PROJECTILE_COUNT,
  NUCLEAR_PLASMA_FOURTH_CHAINFIRE_SHOT_COST, NUCLEAR_PLASMA_PROJECTILE_COUNT,
  NUCLEAR_PLASMA_RECHARGE_AMOUNT, NUCLEAR_PLASMA_RECHARGE_DELAY, NUCLEAR_PLASMA_RECHARGE_TICK,
  NUCLEAR_PLASMA_SECOND_CHAINFIRE_PROJECTILE_COUNT, NUCLEAR_PLASMA_SECOND_CHAINFIRE_SHOT_COST,
  NUCLEAR_PLASMA_SEVENTH_CHAINFIRE_PROJECTILE_COUNT, NUCLEAR_PLASMA_SEVENTH_CHAINFIRE_SHOT_COST,
  NUCLEAR_PLASMA_SHOT_COST, NUCLEAR_PLASMA_SIXTH_CHAINFIRE_PROJECTILE_COUNT,
  NUCLEAR_PLASMA_SIXTH_CHAINFIRE_SHOT_COST, NUCLEAR_PLASMA_THIRD_CHAINFIRE_PROJECTILE_COUNT,
  NUCLEAR_PLASMA_THIRD_CHAINFIRE_SHOT_COST, NULL_POINTER_BEHAVIOR, NULL_POINTER_PROJECTILE_COUNT,
  NULL_POINTER_SHOT_COST, PISTOL_AIMED_ACCURACY_BONUS, PISTOL_AIMED_FIRE_COST_MULTIPLIER,
  PISTOL_BEHAVIOR, PISTOL_PROJECTILE_COUNT, PLASMA_RIFLE_BEHAVIOR,
  PLASMA_RIFLE_CHAINFIRE_PROJECTILE_COUNT, PLASMA_RIFLE_CHAINFIRE_SHOT_COST,
  PLASMA_RIFLE_PROJECTILE_COUNT, PLASMA_RIFLE_SECOND_CHAINFIRE_PROJECTILE_COUNT,
  PLASMA_RIFLE_SECOND_CHAINFIRE_SHOT_COST, PLASMA_RIFLE_SHOT_COST, PLASMA_SHOTGUN_BEHAVIOR,
  PLASMA_SHOTGUN_PROJECTILE_COUNT, PLASMA_SHOTGUN_SHOT_COST, PassiveModifier, PassiveStat,
  PeriodicEffect, RAILGUN_BEHAVIOR, RAILGUN_PROJECTILE_COUNT, RAILGUN_SHOT_COST,
  REVENANTS_LAUNCHER_BEHAVIOR, ROCKET_LAUNCHER_BEHAVIOR, ROCKET_LAUNCHER_PROJECTILE_COUNT,
  ResourceCost, SHOTGUN_BEHAVIOR, SHOTGUN_KNOCKBACK_DISTANCE, SUBTLE_KNIFE_BEHAVIOR,
  SUPER_SHOTGUN_BEHAVIOR, SUPER_SHOTGUN_PROJECTILE_COUNT, StatusCost, StatusEffect,
  TRIGUN_BEHAVIOR, TRIGUN_PROJECTILE_COUNT, TRIGUN_SHOT_COST, TRISTAR_BLASTER_BEHAVIOR,
  TRISTAR_BLASTER_PROJECTILE_COUNT, TRISTAR_BLASTER_SHOT_COST, TargetOrder, TargetProperty,
  TargetSelectionPolicy, TargetSource, WeaponRechargeOutcome, WeaponRechargePolicy,
  WeaponRechargeState, bfg10k_chainfire_profile, chaingun_chainfire_profile,
  laser_rifle_chainfire_profile, minigun_chainfire_profile, nuclear_plasma_chainfire_profile,
  plasma_rifle_chainfire_profile,
};
pub use bfg10k::{
  BFG10K_EXPLOSION_DAMAGE_DICE, BFG10K_EXPLOSION_DAMAGE_DIE_SIDES,
  BFG10K_GROUND_ITEM_DESTRUCTION_THRESHOLD, knockback_distance, radius_two_blast_positions,
  roll_explosion_damage, should_destroy_bfg10k_ground_item,
};
pub use bfg9000::{
  BFG9000_EXPLOSION_DAMAGE_DICE, BFG9000_EXPLOSION_DAMAGE_DIE_SIDES,
  BFG9000_GROUND_ITEM_DESTRUCTION_THRESHOLD, radius_eight_blast_positions,
  should_destroy_bfg9000_ground_item,
};
pub use chainfire::{
  ChainfireBurst, ChainfireState, ChainfireWeapon, advance_level as advance_chainfire_level,
  chainfire_burst, chainfire_profile, reset_level as reset_chainfire_level,
};
pub use chaingun::{
  CHAINGUN_CHAINFIRE_PROJECTILE_COUNT, CHAINGUN_CHAINFIRE_SHOT_COST, ChainfireTransition,
  ChaingunTransition, MinigunTransition,
};
pub use combat::CombatResolver;
pub use combat_shotgun::COMBAT_SHOTGUN_ALT_RELOAD_CAP;
pub use content_validation::{ContentValidationError, validate_current_content};
pub use environment::{
  FLUID_MOVEMENT_COST, HazardDamage, MUD_MOVEMENT_COST, entered_tile_damage, movement_cost,
};
pub use fov::{DEFAULT_VISION_RADIUS, compute_fov, has_line_of_sight, line_points};
pub use game::{Game, GameState};
pub use generator::{GeneratedLevel, LevelGenerator, LevelGeneratorConfig, MonsterSpawn, Room};
pub use grammaton::{GRAMMATON_MODE_SCORE_COST, GrammatonTransition};
pub use grid::{Map, Tile};
pub use inventory::{DEFAULT_INVENTORY_CAPACITY, Equipment, Inventory};
pub use item::Item;
pub use jackhammer::{JACKHAMMER_MODE_SCORE_COST, JackhammerTransition};
pub use level_definition::{LEVEL_DEFINITIONS, LevelDefinition, standard_procedural};
pub use malek_armor::{
  MALEK_ARMOR_RECHARGE_AMOUNT, MALEK_ARMOR_RECHARGE_DELAY, MALEK_ARMOR_RECHARGE_TICK,
};
pub use missile_launcher::MISSILE_LAUNCHER_ALT_RELOAD_CAP;
pub use nuclear_bfg9000::{
  NUCLEAR_BFG9000_EXPLOSION_DAMAGE_DICE, NUCLEAR_BFG9000_EXPLOSION_DAMAGE_DIE_SIDES,
  radius_eight_blast_positions as nuclear_bfg9000_radius_eight_blast_positions,
  roll_explosion_damage as roll_nuclear_bfg9000_explosion_damage,
};
pub use nuclear_bfg9000::{
  NUCLEAR_BFG9000_GROUND_ITEM_DESTRUCTION_THRESHOLD, should_destroy_nuclear_bfg9000_ground_item,
};
pub use nuclear_overload::{
  NUCLEAR_OVERLOAD_FLOOR_COUNTDOWN, NUCLEAR_OVERLOAD_HAZARD_COUNTDOWN, NUCLEAR_OVERLOAD_SCORE_COST,
};
pub use nuke::{NukeError, NukeState};
pub use pump_action::PUMP_ACTION_COST;
pub use replay::ReplayEngine;
pub use resistance::apply_damage_resistance;
pub use rng::GameRng;
pub use rocket_launcher::{
  ROCKET_LAUNCHER_EXPLOSION_DAMAGE_DICE, ROCKET_LAUNCHER_EXPLOSION_DAMAGE_DIE_SIDES,
  ROCKET_LAUNCHER_EXPLOSION_DELAY, ROCKET_LAUNCHER_EXPLOSION_KNOCKBACK,
  ROCKET_LAUNCHER_EXPLOSION_RADIUS, ROCKET_LAUNCHER_GROUND_ITEM_DESTRUCTION_THRESHOLD,
  apply_distance_falloff, radius_four_blast_positions,
  roll_explosion_damage as roll_rocket_launcher_explosion_damage,
};
pub use scenario::{Scenario, ScenarioRunner};
pub use scheduler::{ACTION_THRESHOLD, Scheduler};
pub use special_level_definition::{
  SPECIAL_LEVEL_DEFINITIONS, SpecialLevelDefinition, at_legacy_depth, by_id,
};
pub use subtle_knife::{
  SUBTLE_KNIFE_HP_COST, SUBTLE_KNIFE_SCORE_COST, SUBTLE_KNIFE_TARGET_DAMAGE, SubtleKnifeCost,
  SubtleKnifeError, SubtleKnifeTransition, TiredStatus,
};
pub use targeting::TargetingSystem;
pub use trigun::{
  TRIGUN_HP_COST, TRIGUN_MAX_HP_COST, TRIGUN_MIN_HP, TRIGUN_MIN_MAX_HP, TRIGUN_NUKE_TIMER,
  TRIGUN_SCORE_COST, TrigunCost, TrigunError, TrigunTransition,
};
pub use world::World;

/// Returns the core simulation engine name.
#[must_use]
pub fn engine_name() -> &'static str {
  "drl-core"
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_engine_name() {
    assert_eq!(engine_name(), "drl-core");
  }
}
